import {
  LayoutDashboard,
  CircleDollarSign,
  Users,
  BedDouble,
  Microscope,
  Pill,
  UtensilsCrossed,
  Gauge,
  Wallet,
  HeartPulse,
  BarChart3,
  Settings,
} from "lucide-react";

export const sidebarMenu = [
  {
    icon: LayoutDashboard,
    title: "Dashboard",
    path: "/",
  },
  {
    icon: CircleDollarSign,
    title: "Revenue",
    path: "/revenue",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Daily Revenue", tab: "daily" },
      { title: "Department Revenue", tab: "department" },
      { title: "Collections", tab: "collections" },
      { title: "Discounts", tab: "discounts" },
      { title: "Refunds", tab: "refunds" },
      { title: "Insurance Revenue", tab: "insurance" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: Users,
    title: "Patients",
    path: "/patients",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "OP Patients", tab: "opd" },
      { title: "IP Patients", tab: "ipd" },
      { title: "New vs Repeat", tab: "retention" },
      { title: "Demographics", tab: "demographics" },
      { title: "Doctor Load", tab: "doctor" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: BedDouble,
    title: "Bed Management",
    path: "/beds",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "ICU Occupancy", tab: "icu" },
      { title: "General Ward", tab: "ward" },
      { title: "Deluxe Rooms", tab: "deluxe" },
      { title: "Ventilator Usage", tab: "ventilator" },
      { title: "Availability Status", tab: "availability" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: Microscope,
    title: "Lab & Radiology",
    path: "/lab",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Pathology Tests", tab: "pathology" },
      { title: "Radiology Scans", tab: "radiology" },
      { title: "Turnaround Time (TAT)", tab: "tat" },
      { title: "Pending Reports", tab: "pending" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: Pill,
    title: "Pharmacy",
    path: "/pharmacy",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Daily Sales", tab: "sales" },
      { title: "Inventory Alerts", tab: "inventory" },
      { title: "Near Expiry", tab: "expiry" },
      { title: "Refunds", tab: "refunds" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: UtensilsCrossed,
    title: "Kitchen & Diet",
    path: "/kitchen-diet",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Meal Production", tab: "production" },
      { title: "Diet Categories", tab: "diet" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: Gauge,
    title: "Operations",
    path: "/operations",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Doctor Utilization", tab: "doctor" },
      { title: "Admission Trend", tab: "admission" },
      { title: "ALOS", tab: "alos" },
      { title: "Emergency", tab: "emergency" },
      { title: "Peak Hours", tab: "peak" },
      { title: "Insurance", tab: "insurance" },
      { title: "Department Efficiency", tab: "department" },
      { title: "Upload", tab: "upload" },
    ],
  },
  {
    icon: Wallet,
    title: "Doctors Payout",
    path: "/doctors",
    tabs: [
      { title: "Payout Overview", tab: "overview" },
      { title: "Doctor-wise Payout", tab: "doctor" },
      { title: "Department Payout", tab: "department" },
      { title: "Service Revenue", tab: "service" },
      { title: "Revenue Contribution", tab: "contribution" },
      { title: "Monthly Trend", tab: "trend" },
      { title: "Pending Payout", tab: "pending" },
      { title: "TDS & Deductions", tab: "tds" },
      { title: "Top Doctors", tab: "top" },
      { title: "Upload", tab: "upload" },
    ],
  },
  {
    icon: HeartPulse,
    title: "Nursing",
    path: "/nursing",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Midnight Census Report", tab: "midnight-census" },
      { title: "Data Upload", tab: "upload" },
    ],
  },
  {
    icon: BarChart3,
    title: "Reports",
    path: "/reports",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Revenue Reports", tab: "revenue" },
      { title: "Patient Reports", tab: "patient" },
      { title: "Pharmacy Reports", tab: "pharmacy" },
      { title: "Lab Reports", tab: "lab" },
      { title: "Bed Reports", tab: "bed" },
      { title: "Drill Down", tab: "drill" },
      { title: "Export PDF", tab: "pdf" },
      { title: "Export Excel", tab: "excel" },
      { title: "Schedule", tab: "schedule" },
    ],
  },
  {
    icon: Settings,
    title: "Settings",
    path: "/settings",
    tabs: [
      { title: "Overview", tab: "overview" },
      { title: "Profile", tab: "profile" },
      { title: "User Roles", tab: "users" },
      { title: "Module Configuration", tab: "modules" },
      { title: "Notifications", tab: "notifications" },
      { title: "Branch", tab: "branch" },
      { title: "Security", tab: "security" },
      { title: "Backup", tab: "backup" },
      { title: "Data Refresh", tab: "refresh" },
      { title: "System Logs", tab: "logs" },
    ],
  },
];
